openapi: 3.1.0
info:
  title: API для проекта «Шесть городов»
  description: «Шесть городов» — сервис для путешественников, не желающих переплачивать за аренду жилья. Выбирайте один из шести популярных городов для путешествий и получайте актуальный список предложений по аренде.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags: 
  - name: offers
    description: Действия с объявлениями
  - name: comments
    description: Действия с комментариями
  - name: users
    description: Действия с пользователями
paths:
  /users/register:
    post: 
      tags:
        - users
      summary: Регистрация нового пользователя
      description: Регистрирует нового пользователя

      requestBody:
        description: Информация для создания нового пользователя.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
      responses:
        '201':
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/RegularUser'
                  - $ref: '#/components/schemas/ProUser'
        '409':
          description: Пользователь с таким email уже существует.

  /users/login:
    post: 
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
    get: 
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию о состоянии пользователя
  /users/{userId}/avatar:
    post: 
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение аватара должно быть в формате `png` или `jpg`.

components:
  schemas:
    createUser:
      type: object

      properties:
        email: 
          type: string
          example: test@test.ru
          format: email
        name:
          type: string
          example: Александр Петров
        password:
          type: string
          example: 123456

    RegularUser:
      type: object 

      properties:
        id: 
            type: string
            example: fb3y84f738g4f3894v2g72gc27
            format: uuid
        email: 
          type: string
          example: test@test.ru
          format: email
        name:
          type: string
          example: Александр Петров
        isPro: 
          type: boolean
          default: false
        password:
          type: string
          example: 123456
        avatar:
          type: string
          example: https://avatar.org/12
          format: uri
          nullable: true

    ProUser:
      type: object 

      properties:
        id: 
            type: string
            example: fb3y84f738g4f3894v2g72gc27
        email: 
          type: string
          example: test@test.ru
        name:
          type: string
          example: Александр Петров
        isPro: 
          type: boolean
          default: true
        password:
          type: string
          example: 123456
        avatar:
          type: string
          example: https://avatar.org/12
          format: uri
          nullable: true